# listening address of transocks.
listen = "0.0.0.0:12345"    # default is "localhost:1081"

proxy_url = "socks5://127.0.0.1:8087"  # for SOCKS5 server
#proxy_url = "http://10.20.30.40:3128"   # for HTTP proxy server

[log]
#filename = "/path/to/file"   # default to stderr
level = "info"               # critical", error, warning, info, debug
#format = "json"              # plain, logfmt, json
