# nikola
# nkl_Ver=7.6.4
# py_Ver=py2
# select pypi-index-url $PP_index
# docker build --force-rm --no-cache --rm -f Dockerfile-nikola-arc -t nikola:$nkl_Ver$py_Ver .
# docker run -u 1000 --rm -p 8000:8000 -v $(pwd):/blog -w /blog -t -i nikola:$nkl_Ver$py_Ver /usr/bin/bash
FROM arch:1508
MAINTAINER shmilee <shmilee.zju@gmail.com>

RUN nkl_Ver=7.6.4 && \
    py_Ver=py2 && \
    py3_packages=(python-pip \
        python-pygments \
        python-pillow \
        python-dateutil=2.4.2 \
        python-docutils \
        python-mako \
        python-unidecode \
        python-lxml \
        python-blinker \
        python-setuptools \
        python-requests \
        python-markdown \
        python-jinja \
        python-webassets \
        python-pyzmq ) && \
    py2_packages=($(echo ${py3_packages[@]}|sed 's/python/&2/g')) && \
    PP_index='https://pypi.tuna.tsinghua.edu.cn/simple' && \
    PP_index='https://pypi.python.org/simple' && \
    nkl_Url='https://raw.githubusercontent.com/getnikola/nikola' && \
    curl -O "$nkl_Url/v$nkl_Ver"/requirements.txt && \
    curl -O "$nkl_Url/v$nkl_Ver"/requirements-extras.txt && \
    sed -i 's/^ipython.note.*$/ipython[notebook]==3.2.1/' requirements-extras.txt && \
    sed -i -e '/ipython/d' -e '/pyphen/d' -e '/ghp-import/d' requirements-extras.txt && \
    useradd -m -g users -G wheel -s /bin/bash -d /blog -u 1000 shmilee && \
    if [[ $py_Ver == py3 ]]; then \
        pacman -Syu --noconfirm ${py3_packages[@]} && \
        pip3 install -i "$PP_index" -r requirements-extras.txt nikola=="$nkl_Ver" && \
        find /usr/lib/python3* \
		    \( -type d -a -name test -o -name tests \) \
		    -exec rm -rf '{}' + ; \
    elif [[ $py_Ver == py2 ]]; then \
        pacman -Syu --noconfirm ${py2_packages[@]} && \
        pip2 install -i "$PP_index" -r requirements-extras.txt nikola=="$nkl_Ver" && \
        find /usr/lib/python2* \
		    \( -type d -a -name test -o -name tests \) \
		    -exec rm -rf '{}' + ; \
    fi && \
    rm -rf /usr/share/{man/*,doc/*,gtk-doc/,info/} /{root,tmp} && \
    rm -r /var/cache/pacman/pkg/* && \
    rm -r /var/lib/pacman/sync/*
#    pacman -Rsn --noconfirm python-pip

#ENTRYPOINT ["nikola"]
#CMD ["help"]
